### ISSUE TITLE
Prolems initializing

### ISSUE THREAD

**Issue by blynx** [erikengervall/parallax-vanilla#1]
Hi,

pretty neat little vanilla library, thank you for sharing!
I had some minor problems initializing the library:

In the documentation the attributes are named `para-speed=x`, etc. but it has to be `pv-speed=x`, etc.
Then, `settingsDefault.block.class` should be "para-block" ;)

Cheers,
Steffen

**Comment by erikengervall** [comment]
Hey Steffen!

I'm glad you enjoy the library and thanks for the feedback, I resolved the name-confusion in the latest version :)

/Erik
