### ISSUE TITLE
scrollTop undefined

### ISSUE THREAD

**Issue by pedzed** [erikengervall/parallax-vanilla#4]
Running Chrome on Linux, I get the following error:
```
Uncaught TypeError: Cannot set property 'scrollTop' of undefined
```
(Possibly related to https://stackoverflow.com/q/20514596)

On Firefox I get this (perhaps unrelated) error:
```
TypeError: pv.windowProps is undefined
TypeError: pv.containerArr is undefined
```

**Comment by erikengervall** [comment]
I'm unable to reproduce these errors using Browserstack - what versions of Chrome and Firefox are you using?

**Comment by pedzed** [comment]
I'm not sure and can't check at the moment. But I was running a fairly recent version of Chrome and Firefox Quantum.

**Comment by pedzed** [comment]
I'm not sure and can't check at the moment. But I was running a fairly recent version of Chrome and Firefox Quantum.

Although I doubt it, perhaps it was just my code that failed, but it's not important for me personally. I created this issue in case others stumble on the same problem.

The basic parallax of pure CSS satisfies my needs (`background-attachment: fixed`).

**Comment by gabemartin** [comment]
I fixed this issue by moving the script out of the `<head>` and down to the bottom of the page right before the closing `</body>` tag.

**Comment by erikengervall** [comment]
I'm glad it worked out!
