### ISSUE TITLE
Initialization Errors

### ISSUE THREAD

**Issue by ekfuhrmann** [erikengervall/parallax-vanilla#5]
Everytime I try and initialize this, I get the following ERRORs:

![image](https://user-images.githubusercontent.com/8878152/39015686-3004f5e8-43ec-11e8-8b1f-0f8c077cd126.png)

**Comment by erikengervall** [comment]
Could you provide some more details in regards to for example OS/Browser?

**Comment by ekfuhrmann** [comment]
Sure, I was getting this in Firefox Developer Edition 60.0b14 (64-bit) on macOS High Sierra (10.13.1).

**Comment by erikengervall** [comment]
I cannot replicate this on my machine (also macOS), even for various versions of Firefox. I've committed a bunch of refactoring that might help - please try it. Please open a new issue if the issue persist and if so include some code :)
