### ISSUE TITLE
Initialization problem

### ISSUE THREAD

**Issue by webmazz** [erikengervall/parallax-vanilla#6]
Hi!
I have problem with initialization this plugin.

When I put  `pv.init ()` in the end of the <body> tag  everything works but I need to start the plugin when everything is loaded.

I tried this way:

`$(window).on('load', function() {
    pv.init();
});`

and I have this error in console:

`Uncaught TypeError: Cannot set property 'scrollTop' of undefined
    at module.exports (parallax-vanilla.js:442)
    at mainLoop (parallax-vanilla.js:406)`

How can I solve this problem?

**Comment by joshkrz** [comment]
Same problem here but even adding the init function right after the block it still results in the same error.

**Comment by erikengervall** [comment]
Haven't been able to replicate this myself. Are you using any odd browsers?

**Comment by erikengervall** [comment]
Could not reproduce.
